version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4100:4100"
    environment:
      - NODE_ENV=production
    mem_limit: 400m
    # volumes:
    #   - .:/app
    #   - /app/node_modules